name: Metrics
on:
  # Se actualiza cada 24 horas automáticamente
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu usuario de GitHub
          user: edwinmoreno77
          token: ${{ secrets.METRICS_TOKEN }}
          # Opciones de diseño
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Santiago
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
